version: 0.0
os: linux
files:
  - source: /
    destination: /var/nodeapp/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
